# ref: https://docs.helix-editor.com/install.html#ubuntu

- name: "Add the 'helix' ppa"
  ansible.builtin.apt_repository:
    repo: 'ppa:maveonair/helix-editor'
  become: true
  become_user: root

- name: "Install the 'helix' application package"
  ansible.builtin.package:
    name: helix
    state: present
  become: true
  become_user: root

